PhotoAlbum3/Controllers/ListImagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PhotoAlbum3.Models;
using PhotoAlbum3.Utils;

namespace PhotoAlbum3.Controllers
{

    public class ListImagesController : Controller
    {
        private PhotoAlbum3DBContext db = new PhotoAlbum3DBContext( );


        //
        // GET: /ListImages/

        public ActionResult Index( )
        {
            string user_name = getActiveUserName( );
            ViewBag.AvailAbleTags = new SelectList( db.ImageTags, "ID", "TagName" );
            ViewBag.AvailAbleLocations = new SelectList( db.Locations, "ID", "Description" );
            return View( db.PhotoImages.Include( p => p.Location ).Where( p => ( p.privacy == 1 && p.Owner.UserName == user_name ) || p.privacy == 2 ) );
        }


        [HttpPost]
        public ActionResult Search( )
        {
            string[] tagArray = Request.Form["items"].Split( ',' );
            string user_name = getActiveUserName( );
            List<int> ids = new List<int>( );
            foreach ( string s in tagArray )
            {
                ids.Add( int.Parse( s ) );
            }
            IQueryable<PhotoImage> photos = db.PhotoImages.Where( p => p.TagsList.Any( x => ids.Contains( x.ID ) ) && ( ( p.privacy == 1 && p.Owner.UserName == user_name ) || p.privacy == 2 ) );
            ViewBag.AvailAbleTags = new SelectList( db.ImageTags, "ID", "TagName" );

            return View( "Index", photos );
        }

        //
        // GET: /ListImages/Details/5

        public ActionResult Details( int id = 0 )
        {
            //PhotoImage photoimage = db.PhotoImages.Find( id );

            string user_name = getActiveUserName( );
            PhotoImage photoimage;
            try
            {
                photoimage = db.PhotoImages.Single( p => ( ( p.privacy == 1 && p.Owner.UserName == user_name ) || p.privacy == 2 ) && p.ID == id );
            }
            catch ( Exception )
            {
                ViewBag.Error = "Photo is private or deleted!";
                return View( "Errors" );
            }

            Comment[] imgComment = ( from c in db.Comments where c.ImageId == id select c ).ToArray( );

            ViewBag.Comments = ( imgComment == null ) ? new Comment[0] : imgComment;
            if ( photoimage == null )
            {
                ViewBag.Error = "Photo is private or deleted!";
                return View( "Errors" );
            }
            return View( photoimage );
        }

        //
        // GET: /ListImages/Create
        [Authorize]
        public ActionResult Create( )
        {
            ViewBag.LocationId = new SelectList( db.Locations, "ID", "coordinates" );
            ViewBag.AvailAbleTags = new SelectList( db.ImageTags, "ID", "TagName" );
            return View( );
        }

        //
        // POST: /ListImages/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create( PhotoImage photoimage )
        {
            if ( ModelState.IsValid )
            {

                string user_name = getActiveUserName( );


                photoimage.OwnerId = GetActiveUserId( );

                string[] tmp = Request.Form["items"].Split( ',' );

                //photoimage.TagsList = db.ImageTags.Where( x => tmp.Contains( x.ID.ToString( ) ) ) as ICollection<ImageTags>;

                photoimage.TagsList = new List<ImageTags>( );
                foreach ( string s in tmp )
                {
                    int tmpId = int.Parse( s );
                    photoimage.TagsList.Add( db.ImageTags.Single( x => x.ID == tmpId ) );
                }
                SaveImageUtil.SaveImage( photoimage, Request, Server, "fileUpload", "Images" );
                db.PhotoImages.Add( photoimage );

                db.SaveChanges( );
                return RedirectToAction( "Index" );
            }

            ViewBag.LocationId = new SelectList( db.Locations, "ID", "coordinates", photoimage.LocationId );
            return View( photoimage );
        }



        [Authorize]
        [HttpPost]
        public ActionResult PublishComment( string pic_id, string comment )
        {
            if ( ModelState.IsValid )
            {

                Comment c = new Comment( );
                c.ImageId = int.Parse( pic_id );
                c.Text = comment;

                c.UserId = GetActiveUserId( );

                db.Comments.Add( c );
                db.SaveChanges( );

            }

            int tmpPicId = int.Parse( pic_id );
            Comment[] imgComment = ( from c in db.Comments where c.ImageId == tmpPicId select c ).Include( u => u.User ).ToArray( );

            ViewBag.Comments = ( imgComment == null ) ? new Comment[0] : imgComment;

            PhotoImage imgTMP = db.PhotoImages.Find( int.Parse( pic_id ) );
            return View( "Details", imgTMP );
        }


        //
        // GET: /ListImages/Edit/5
        [Authorize]
        public ActionResult Edit( int id = 0 )
        {
            PhotoImage photoimage;
            try
            {
                string user_name = getActiveUserName( );
                photoimage = CheckActiveUserOwnership( id );

                ViewBag.LocationId = new SelectList( db.Locations, "ID", "coordinates", photoimage.LocationId );
                MultiSelectList lista = new MultiSelectList( db.ImageTags, "ID", "TagName", photoimage.TagsList.Select( x => x.ID.ToString() ) );
                ViewBag.ListImageTags = lista;
            }
            catch ( Exception )
            {
                ViewBag.Error = "You don't have privilegies to edit!";
                return View( "Errors" );
            }
            if ( photoimage == null )
            {
                ViewBag.Error = "Picture deleted or insuficient privilegies";
                return View( "Errors" );
            }


            return View( photoimage );
        }

        //
        // POST: /ListImages/Edit/5
        [Authorize]
        [HttpPost]
        public ActionResult Edit( PhotoImage photoimage )
        {
            if ( ModelState.IsValid )
            {
                PhotoImage tmpImage = db.PhotoImages.Find( photoimage.ID );

                //List<int> tmp = Request.Form["items"].Split( ',' ).Select(x=>int.Parse(x)).ToList<int>();
                //IQueryable<ImageTags> tmpTags = db.ImageTags.Where( x => tmp.Contains( x.ID ) );
                  
                    
                    //( db.ImageTags.Where( x => tmp.Contains( x.ID ) ) );
                tmpImage.privacy = photoimage.privacy;
                tmpImage.LocationId = photoimage.LocationId;

                db.Entry( tmpImage ).State = EntityState.Modified;
                db.SaveChanges( );
                return RedirectToAction( "Index" );
            }

            return View( photoimage );
        }

        //
        // GET: /ListImages/Delete/5
        [Authorize]
        public ActionResult Delete( int id = 0 )
        {
            PhotoImage photoimage = db.PhotoImages.Find( id );
            if ( photoimage == null )
            {
                ViewBag.Error = "You don't have privilegies to delete!";
                return View( "Errors" );
                //return HttpNotFound( );
            }
            return View( photoimage );
        }

        //
        // POST: /ListImages/Delete/5

        [HttpPost, ActionName( "Delete" )]
        public ActionResult DeleteConfirmed( int id )
        {
            string user_name = getActiveUserName( );
            try
            {
                PhotoImage photoimage = CheckActiveUserOwnership( id );
                db.PhotoImages.Remove( photoimage );
                db.SaveChanges( );
            }
            catch ( Exception )
            {
                //ViewBag.Error = "You don't have privilegies to edit!";
                ViewBag.Error = "Picture deleted or insuficient privilegies";
                return View( "Errors" );
            }
            return RedirectToAction( "Index" );
        }


        protected override void Dispose( bool disposing )
        {
            db.Dispose( );
            base.Dispose( disposing );
        }

        private string getActiveUserName( )
        {
            return HttpContext.Request.RequestContext.HttpContext.User.Identity.Name;
        }

        private PhotoImage CheckActiveUserOwnership( int id )
        {
            string user_name = getActiveUserName( );
            return db.PhotoImages.Single( p => p.ID == id && p.Owner.UserName == user_name );
        }

        private int GetActiveUserId( )
        {
            string user_name = getActiveUserName( );
            return db.UserProfiles.Single( x => x.UserName == user_name ).UserId;
        }
    }
}

PhotoAlbum3/Views/ListImages/Create.cshtml
@model PhotoAlbum3.Models.PhotoImage

@{
    ViewBag.Title = "Create";
}


<h2>Add new Photo</h2>

@using ( Html.BeginForm( "Create", "ListImages", FormMethod.Post, new { enctype = "multipart/form-data" } ) )
{
    @Html.ValidationSummary( true )

    <fieldset>
        <legend>PhotoImage</legend>

        <div class="editor-label">
            @Html.LabelFor( model => model.Location.description, "Location" )
        </div>
        <div class="editor-field">
            @Html.DropDownList( "LocationId", string.Empty )
            @Html.ValidationMessageFor( model => model.Location.description )
        </div>

        <div>
            @Html.ActionLink( "Add Location", "Create", "Location" )
            </div>


        <div class="editor-field">
            <input type="file" name="fileUpload" />
        </div>


        <div class="editor-label">
            @Html.LabelFor( model => model.privacy )
        </div>
        <div class="editor-field">
            <label class="radioButtonCreate">@Html.RadioButtonFor( m => m.privacy, 1 ) Private</label>
            <label class="radioButtonCreate">@Html.RadioButtonFor( m => m.privacy, 2 ) Public</label>
            @Html.ValidationMessageFor( model => model.privacy )
        </div>
        
        <label>Tags:</label>
        
        
        @Html.DropDownList("items",(SelectList)ViewBag.AvailAbleTags, new {style="width: 350px;", multiple="multiple", @class="chzn-select", tabindex="8"})

        

        <!--<select style="width: 350px;" multiple="multiple" class="chzn-select" id="items" name="items" tabindex="8">
            @*foreach ( PhotoAlbum3.Models.ImageTags item in ViewBag.AvailAbleTags )
            {
                <option value="@item.ID">@item.TagName</option> 
            }*@
        </select>-->
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink( "Back to List", "Index" )
</div>

@section Scripts {
    @Scripts.Render( "~/bundles/jqueryval" )
    @Styles.Render( "~/Content/chosen.css" )
    @Scripts.Render( "~/Scripts/chosen/chosen.jquery.js" )
    @Scripts.Render( "~/Scripts/TagoviSkripta.js" )
}

PhotoAlbum3/Views/ListImages/Delete.cshtml
@model PhotoAlbum3.Models.PhotoImage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PhotoImage</legend>

    

    <div class="display-field">
        <img src="@Model.LargeURL" alt=""/>
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PhotoAlbum3/Views/ListImages/Details.cshtml
@model PhotoAlbum3.Models.PhotoImage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>PhotoImage</legend>

    <div class="details_UserName">
    <b>    @Html.DisplayNameFor( model => model.Owner.UserName ): </b>
    
        @Html.DisplayFor( model => model.Owner.UserName )
    </div>

    <div class="display-field">
        <img src="@Model.LargeURL" alt=""/>
    </div>
</fieldset>

<p>
    
    @Html.ActionLink( "Edit", "Edit", new { id = Model.ID } )
    @Html.ActionLink( "Back to List", "Index" )
</p>

@using ( Html.BeginForm( "PublishComment", "ListImages", FormMethod.Post ) )
{
    @Html.Hidden( "pic_id", Model.ID )
    <div>
        <p>@Html.TextArea( "comment" )</p>
        <p>
            <input type="submit" value="Comment!" /></p>
    </div>
}
@using PhotoAlbum3.Models
@Styles.Render( "~/Content/stil1.css" )

@foreach( Comment c in ViewBag.Comments )
{
    <div class="comment">
        <p class="underlined">@c.User.UserName says:</p>
        <p>@c.Text</p>
    </div>
}

PhotoAlbum3/Views/ListImages/Edit.cshtml
@model PhotoAlbum3.Models.PhotoImage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PhotoImage</legend>

        @Html.HiddenFor(model => model.ID)

        

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationId, "Location")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LocationId", String.Empty)
            @Html.ValidationMessageFor(model => model.LocationId)
        </div>

        <div class="display-field">
        <img src="@Model.LargeURL" alt=""/>
    </div>

       
        <div class="editor-label">
            @Html.LabelFor( model => model.privacy )
        </div>
        <div class="editor-field">
            <label class="radioButtonCreate">@Html.RadioButtonFor( m => m.privacy, 1 ) Private</label>
            <label class="radioButtonCreate">@Html.RadioButtonFor( m => m.privacy, 2 ) Public</label>
            @Html.ValidationMessageFor( model => model.privacy )
        </div>

        <label>Tags:</label>       
        @*Html.DropDownList("items",(MultiSelectList)ViewBag.ListImageTags, new {style="width: 350px;", multiple="multiple", @class="chzn-select", tabindex="8"})
        *@
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
@Styles.Render( "~/Content/chosen.css" )
    @Scripts.Render( "~/Scripts/chosen/chosen.jquery.js" )
    @Scripts.Render( "~/Scripts/TagoviSkripta.js" )
}

PhotoAlbum3/Views/ListImages/Errors.cshtml
@{
    ViewBag.Title = "Errors";
}

<h2>Errors</h2>

<div>
    <b>Error: </b>
    @ViewBag.Error
    </div>
<p></p>
@Html.ActionLink( "Return to Index","Index" )

PhotoAlbum3/Views/ListImages/Index.cshtml
@model IEnumerable<PhotoAlbum3.Models.PhotoImage>

@{
    ViewBag.Title = "Index";
}

<h2>Pictures</h2>

<p>
    @Html.ActionLink( "Add New Picture", "Create" )
</p>
<p>
    @using ( Html.BeginForm( "Search", "ListImages", FormMethod.Post ) )
    {
        @Html.Display( "Search:" )
        @Html.DropDownList( "items", ( SelectList ) ViewBag.AvailAbleTags, new { style = "width: 350px;", multiple = "multiple", @class = "chzn-select", tabindex = "8" } )
        
        <input type="submit" value="Search" />
    }
</p>

@foreach ( var item in Model )
{
    <div class="pics_wrapper">
    <div class="small_pics_wrapper">
        <div class="@(( item.privacy == 1 ) ? "private_pic" : "public_pic")">
            <a href="@(Url.Action( "Details", "ListImages", new { id = item.ID } ))">
                <img src="@(item.LargeURL)" alt=""/>
            </a>
        </div>
        @Html.ActionLink( "Edit", "Edit", new { id = item.ID } ) | 
            @Html.ActionLink( "Delete", "Delete", new { id = item.ID } ) |
        @Html.ActionLink( "Details", "Details", new { id = item.ID } )
    </div>
    </div>    
}


@section Scripts {
    @Scripts.Render( "~/bundles/jqueryval" )
    @Styles.Render( "~/Content/chosen.css" )
    @Scripts.Render( "~/Scripts/chosen/chosen.jquery.js" )
    @Scripts.Render( "~/Scripts/TagoviSkripta.js" )
}